# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0004_auto_20170315_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tennis.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='btmno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
